changelog:
  exclude:
    labels:
      - no releasenotes
  categories:
    - title: Major Changes 🛠
      labels:
        - major
    - title: New Features 🎉
      labels:
        - enhancement
        - style
    - title: Bugfixes 🐛
      labels:
        - bug
    - title: Documentation 📖
      labels:
        - documentation
    - title: Maintenance 🔧
      labels:
      - "*"
