services:
  redis:
    image: redis:latest
    ports:
      - "6382:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 20s
      retries: 2
      start_period: 40s
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - .:/app
      - temp_updates:/app/temp_updates
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/${REDIS_DB}
      - CELERY_RESULT_BACKEND=redis://redis:6379/${REDIS_DB}
    depends_on:
      redis:
        condition: service_healthy
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8005", "--workers", "2"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8505:8505"
    volumes:
      - .:/app
      - temp_updates:/app/temp_updates
    environment:
      - PYTHONUNBUFFERED=1
      - MURRAY_PASSWORD=${MURRAY_PASSWORD:-}
      # Remove any connection to Redis or Celery
    command: ["streamlit", "run", "app.py", "--server.port=8505", "--server.address=0.0.0.0"]
    # No longer depends on other services
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8505/_stcore/health"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3


  celery_worker:
    build: .
    volumes:
      - .:/app
      - temp_updates:/app/temp_updates
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/${REDIS_DB}
      - CELERY_RESULT_BACKEND=redis://redis:6379/${REDIS_DB}
    depends_on:
      redis:
        condition: service_healthy
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency=2"]
    shm_size: '512m'

  flower:
    build: .
    ports:
      - "5558:5555"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/${REDIS_DB}
      - CELERY_RESULT_BACKEND=redis://redis:6379/${REDIS_DB}
      - CELERY_EVENT_BACKEND=redis://redis:6379/${REDIS_DB}
      - FLOWER_USER=${FLOWER_USER}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD}
    depends_on:
      - celery_worker
    command: ["celery", "-A", "tasks", "flower", "--basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"]

volumes:
  redis_data:    # Volume definition
  temp_updates:  # Volume definition



      