// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar principal con estructura manual organizada
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'Welcome to Murray',
      label: 'Welcome to Murray',
    },
    {
      type: 'doc',
      id: 'Methodology',
      label: 'Methodology',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'tutorial-extras/How to Install',
          label: 'Installation',
        },
        {
          type: 'doc',
          id: 'Murray Python Package/Getting Started',
          label: 'Getting Started',
        },
        {
          type: 'doc',
          id: 'Murray Python Package/Walkthrough',
          label: 'Walkthrough',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'User Guides',
      items: [
        {
          type: 'doc',
          id: 'tutorial-extras/User Guide',
          label: 'Complete Guide',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        {
          type: 'link',
          label: 'Report Issues',
          href: 'https://github.com/entropyx/murray/issues',
        },
      ],
      collapsed: true,
    },
  ],

  // Sidebar alternativo para el blog (si quieres usarlo)
  blogSidebar: [
    {
      type: 'autogenerated',
      dirName: 'blog',
    },
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
