[theme]

# Primary accent for interactive elements
primaryColor="#3A74A6" 

# Background color for the page
backgroundColor="#ffffff"

# Secondary background color for the page
secondaryBackgroundColor="#dee2e6"

# Text color for the page
textColor="#000000"
font="sans serif"