[theme]

# Primary accent for interactive elements
primaryColor="#2a5479" 

# Background color for the page
backgroundColor="#ffffff"

# Secondary background color for the page
secondaryBackgroundColor="#3e7cb1"

# Text color for the page
textColor="#000000"
font="sans serif"


