[theme]

# Primary accent for interactive elements
primaryColor="#1b0043" 

# Background color for the page
backgroundColor="#ffffff"

# Secondary background color for the page
secondaryBackgroundColor="#5f4d7b"

# Text color for the page
textColor="#000000"
font="sans serif"


