[theme]

# Primary accent for interactive elements
primaryColor="#4d4c50" 

# Background color for the page
backgroundColor="#ECEFF2"

# Secondary background color for the page
secondaryBackgroundColor="#8BB0D0"

# Text color for the page
textColor="#211F24"
font="sans serif"


